services:
  - type: web
    name: proxy-solis
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn server:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.10.0
      - key: SOLIS_API_URL
        value: https://academico.faculdadeimes.org.br
      - key: SOLIS_JWT_TOKEN
        sync: false